### 配置实用哪种模式
spring:
  profiles:
    active: dev
### 配置数据库的连接方式
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\\restart1025\\sqlite\\springboot.db
    username:
    password:
### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.restart1025.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

